import Head from "next/head"

const LayoutOne = ({ children }) => {
  return (
    <div style={{ position: 'relative', height: '100vh' }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}

    </div>
  )
}

export default LayoutOne