import { useState, useRef } from 'react';

import Head from 'next/head';

import HTMLFlipBook from 'react-pageflip';

export default function Home() {
  const [name, setName] = useState('');
  let flipBook = useRef(null);

  const flipPage = (e) => {
    // if(name === '') {
    //   flipBook.current.pageFlip().turnToPrevPage()
    //   console.log('you must enter a name')
    // }

  }

  const check = (e) => {
    
    // if(e.data === 'user_fold' || e.data === 'flipping') {
    //   if(name === '') {
    //     console.log('should prevent here')
    //     // e.data = 'read'
    //     flipBook.current.pageFlip().userStop()
    //   }
    // }

  }

  return (
    <div className='mainPage'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HTMLFlipBook ref={flipBook} width={450} height={550} showCover={true} flippingTime={1500} onFlip={flipPage} onChangeState={(e) => check(e)}>
        <div className="cover">

          <h2>Book Cover</h2>

        </div>
        <div className="demoPage" onClick={check}>

          <img src="/imgs/nature.jpg" alt="" />

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, incidunt? Dolores ad deserunt tenetur, sunt beatae voluptate dolor odio rem porro labore repudiandae, iste molestiae nostrum. Voluptas adipisci unde dicta?</p>

        </div>
        <div className="demoPage">

          <img src="/imgs/nature.jpg" alt="" />

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, incidunt? Dolores ad deserunt tenetur, sunt beatae voluptate dolor odio rem porro labore repudiandae, iste molestiae nostrum. Voluptas adipisci unde dicta?</p>

          <button>test</button>

        </div>
        <div className="demoPage">

          <img src="/imgs/nature.jpg" alt="" />

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, incidunt? Dolores ad deserunt tenetur, sunt beatae voluptate dolor odio rem porro labore repudiandae, iste molestiae nostrum. Voluptas adipisci unde dicta?</p>

        </div>
        <div className="demoPage">

          <img src="/imgs/nature.jpg" alt="" />

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, incidunt? Dolores ad deserunt tenetur, sunt beatae voluptate dolor odio rem porro labore repudiandae, iste molestiae nostrum. Voluptas adipisci unde dicta?</p>

        </div>
        <div className="demoPage">

          <img src="/imgs/nature.jpg" alt="" />

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, incidunt? Dolores ad deserunt tenetur, sunt beatae voluptate dolor odio rem porro labore repudiandae, iste molestiae nostrum. Voluptas adipisci unde dicta?</p>

        </div>
        <div className="demoPage">

          <img src="/imgs/nature.jpg" alt="" />

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, incidunt? Dolores ad deserunt tenetur, sunt beatae voluptate dolor odio rem porro labore repudiandae, iste molestiae nostrum. Voluptas adipisci unde dicta?</p>

        </div>
        <div className="cover">

          <h2>Book End</h2>

        </div>

      </HTMLFlipBook>

    </div>
  )
}
